name: CI - Tests and Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run tests with coverage
        run: npm run test -- --coverage

      - name: Upload coverage to GitHub as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Enforce coverage thresholds
        run: |
          node -e "const r=require('./coverage/coverage-summary.json'); const fail = Object.entries(r.total).some(([k,v])=>v.pct < 80); if (fail) { console.error('Global coverage under 80%'); process.exit(1); }"
